apiVersion: apps/v1
kind: Deployment
metadata:
  name: banner-server-deployment
  namespace: banner
  labels:
    app: server-banner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-banner
  template:
    metadata:
      labels:
        app: server-banner
    spec:
      containers:
      - name: server-banner
        image: avishaymp/banner-back:0.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: secret-banner