apiVersion: v1
kind: Service
metadata:
  name: banner-server-service
  namespace: banner
spec:
  selector:
    app: server-banner
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
