apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-server-deployment
  namespace: oms
  labels:
    app: server-oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-oms
  template:
    metadata:
      labels:
        app: server-oms
    spec:
      containers:
      - name: server-oms
        image: avishaymp/oms-back:0.0.2
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: secret-oms