apiVersion: v1
kind: Service
metadata:
  name: oms-server-service
  namespace: oms
spec:
  selector:
    app: server-oms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
