apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-client-conf
  namespace: store
data:
  default.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
      location /assets/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
      }
    }
  ERP_SERVER: http://erp-server-service.erp:3000
  BANNERS_SERVER: http://banner-server-service.banner:3000
  OMS_SERVER: http://oms-server-service.oms:3000