apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-client-conf
  namespace: store
data:
  default.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
      location /assets/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
      }
    }