apiVersion: v1
kind: Service
metadata:
  name: store-server-service
  namespace: store
spec:
  selector:
    app: server-store
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
