apiVersion: v1
kind: Service
metadata:
  name: erp-server-service
  namespace: erp
spec:
  selector:
    app: server-erp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
